# Generated by Django 5.1.6 on 2025-06-11 13:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptCarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChefEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maint_type', models.CharField(blank=True, choices=[('maintenance préventive', 'maintenance préventive'), ('maintenance curative', 'maintenance curative')], max_length=50)),
                ('statut', models.CharField(blank=True, choices=[('Valide', 'Valide'), ('Invalide', 'Invalide')], default='Invalide', max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_consume', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManifacturationArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_consume', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderCarteAcceptation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=200)),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('type_outillage', models.CharField(blank=True, choices=[('Frame', 'Frame'), ('Moule', 'Moule'), ('Tulipe', 'Tulipe'), ('Jaws', 'Jaws')], max_length=100)),
                ('numero_outillage', models.CharField(blank=True, max_length=50)),
                ('ref', models.CharField(blank=True, max_length=50)),
                ('indice', models.CharField(blank=True, max_length=50)),
                ('rmq', models.CharField(blank=True, max_length=200)),
                ('date_ordre', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_ref', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='historicalstock',
            old_name='recieved_commands',
            new_name='received_commands',
        ),
        migrations.RenameField(
            model_name='historicalstock',
            old_name='totale_quatity_used',
            new_name='total_quantity_used',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='recieved_commands',
            new_name='received_commands',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='totale_quatity_used',
            new_name='total_quantity_used',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='quantity',
            new_name='quantity_transacted',
        ),
        migrations.RemoveField(
            model_name='article',
            name='price',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='manifacturation',
            name='prod_date',
        ),
        migrations.RemoveField(
            model_name='manifacturation',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='order',
            name='note',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='type_transaction',
        ),
        migrations.AddField(
            model_name='manifacturation',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manifacturation',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manifacturation',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='historicalstock',
            name='a_commande',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='historicalstock',
            name='consomation_annuelle',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstock',
            name='created_at',
            field=models.DateField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalstock',
            name='delai_approvisionnement',
            field=models.CharField(blank=True, choices=[('1 semaine', '1 semaine'), ('2 semaines', '2 semaines'), ('3 semaines', '3 semaines'), ('4 semaines', '4 semaines'), ('5 semaines', '5 semaines'), ('6 semaines', '6 semaines'), ('7 semaines', '7 semaines'), ('8 semaines', '8 semaines'), ('9 semaines', '9 semaines'), ('10 semaines', '10 semaines'), ('11 semaines', '11 semaines'), ('12 semaines', '12 semaines')], default='1 semaine', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstock',
            name='ecart_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstock',
            name='location',
            field=models.CharField(blank=True, choices=[('Block A', 'Block A'), ('Block B', 'Block B')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalstock',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalstock',
            name='reorder_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstock',
            name='updated_at',
            field=models.DateField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalstock',
            name='virtual_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='manifacturation',
            name='product_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='manifacturation',
            name='quantity_produced',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manifacturation',
            name='status',
            field=models.CharField(blank=True, choices=[('à faire', 'à faire'), ('en cours', 'en cours'), ('terminé', 'terminé')], default='à faire', max_length=10),
        ),
        migrations.AlterField(
            model_name='manifacturation',
            name='status_admin',
            field=models.CharField(blank=True, choices=[('Valide', 'Valide'), ('Invalide', 'Invalide')], default='Invalide', max_length=10),
        ),
        migrations.AlterField(
            model_name='manifacturation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stock',
            name='a_commande',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='consomation_annuelle',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='delai_approvisionnement',
            field=models.CharField(blank=True, choices=[('1 semaine', '1 semaine'), ('2 semaines', '2 semaines'), ('3 semaines', '3 semaines'), ('4 semaines', '4 semaines'), ('5 semaines', '5 semaines'), ('6 semaines', '6 semaines'), ('7 semaines', '7 semaines'), ('8 semaines', '8 semaines'), ('9 semaines', '9 semaines'), ('10 semaines', '10 semaines'), ('11 semaines', '11 semaines'), ('12 semaines', '12 semaines')], default='1 semaine', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ecart_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='location',
            field=models.CharField(blank=True, choices=[('Block A', 'Block A'), ('Block B', 'Block B')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='reorder_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='virtual_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_transac',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('total_quantity_used__gte', 0)), name='used_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('article',), name='unique_article_in_stock'),
        ),
        migrations.AddField(
            model_name='acceptcarte',
            name='manif',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carte_acceptation', to='core.manifacturation'),
        ),
        migrations.CreateModel(
            name='Preventive',
            fields=[
                ('maintenance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.maintenance')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('type_outillage', models.CharField(blank=True, choices=[('Frame', 'Frame'), ('Moule', 'Moule'), ('Tulipe', 'Tulipe'), ('Jaws', 'Jaws'), ('Head', 'Head')], max_length=100)),
                ('atelier', models.CharField(blank=True, choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('B4', 'B4'), ('RSO', 'RSO')], max_length=50)),
                ('numero_outillage', models.CharField(blank=True, max_length=50)),
                ('ref', models.CharField(blank=True, max_length=50)),
                ('gamme_operatoire_main', models.FileField(blank=True, null=True, upload_to='uploads/preventive/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
            ],
            bases=('core.maintenance',),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancearticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.article'),
        ),
        migrations.AddField(
            model_name='maintenancearticle',
            name='maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.maintenance'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='articles',
            field=models.ManyToManyField(blank=True, through='core.MaintenanceArticle', to='core.article'),
        ),
        migrations.AddField(
            model_name='manifacturationarticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.article'),
        ),
        migrations.AddField(
            model_name='manifacturationarticle',
            name='manifacturation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.manifacturation'),
        ),
        migrations.AddField(
            model_name='manifacturation',
            name='articles',
            field=models.ManyToManyField(blank=True, through='core.ManifacturationArticle', to='core.article'),
        ),
        migrations.AddField(
            model_name='ordercarteacceptation',
            name='carte',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='core.acceptcarte'),
        ),
    ]
