# Generated by Django 5.1.6 on 2025-06-11 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_acceptcarte_chefequipe_maintenance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationFrameChefOutillage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_conforme_co', models.CharField(blank=True, choices=[('OK', 'OK'), ('KO', 'KO'), ('NA', 'NA')], max_length=100)),
                ('geo_conforme_co', models.CharField(blank=True, choices=[('OK', 'OK'), ('KO', 'KO'), ('NA', 'NA')], max_length=100)),
                ('marquage_num_co', models.CharField(blank=True, choices=[('OK', 'OK'), ('KO', 'KO'), ('NA', 'NA')], max_length=100)),
                ('visualisation_co', models.CharField(blank=True, choices=[('OK', 'OK'), ('KO', 'KO'), ('NA', 'NA')], max_length=100)),
                ('controle_rotation_co', models.CharField(blank=True, choices=[('OK', 'OK'), ('KO', 'KO'), ('NA', 'NA')], max_length=100)),
                ('protection_tube_co', models.CharField(blank=True, choices=[('OK', 'OK'), ('KO', 'KO'), ('NA', 'NA')], max_length=100)),
                ('scrach_tube_co', models.CharField(blank=True, choices=[('OK', 'OK'), ('KO', 'KO'), ('NA', 'NA')], max_length=100)),
                ('block_swelling_canaux_co', models.CharField(blank=True, choices=[('OK', 'OK'), ('KO', 'KO'), ('NA', 'NA')], max_length=100)),
                ('block_tulipe_canaux_co', models.CharField(blank=True, choices=[('OK', 'OK'), ('KO', 'KO'), ('NA', 'NA')], max_length=100)),
                ('etat_sodure_co', models.CharField(blank=True, choices=[('OK', 'OK'), ('KO', 'KO'), ('NA', 'NA')], max_length=100)),
                ('accept_date', models.DateField(blank=True, null=True)),
                ('accept_signa', models.CharField(blank=True, max_length=200)),
                ('carte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validationframechefoutillage', to='core.acceptcarte')),
            ],
        ),
    ]
