# Generated by Django 5.1.6 on 2025-06-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_validationframechefoutillage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationFrameIngQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_conforme_iq', models.CharField(blank=True, choices=[('OK', 'OK'), ('KO', 'KO'), ('NA', 'NA')], max_length=100)),
                ('geo_conforme_iq', models.CharField(blank=True, choices=[('OK', 'OK'), ('KO', 'KO'), ('NA', 'NA')], max_length=100)),
                ('marquage_num_iq', models.CharField(blank=True, choices=[('OK', 'OK'), ('KO', 'KO'), ('NA', 'NA')], max_length=100)),
                ('visualisation_iq', models.CharField(blank=True, choices=[('OK', 'OK'), ('KO', 'KO'), ('NA', 'NA')], max_length=100)),
                ('controle_rotation_iq', models.CharField(blank=True, choices=[('OK', 'OK'), ('KO', 'KO'), ('NA', 'NA')], max_length=100)),
                ('protection_tube_iq', models.CharField(blank=True, choices=[('OK', 'OK'), ('KO', 'KO'), ('NA', 'NA')], max_length=100)),
                ('scrach_tube_iq', models.CharField(blank=True, choices=[('OK', 'OK'), ('KO', 'KO'), ('NA', 'NA')], max_length=100)),
                ('block_swelling_canaux_iq', models.CharField(blank=True, choices=[('OK', 'OK'), ('KO', 'KO'), ('NA', 'NA')], max_length=100)),
                ('block_tulipe_canaux_iq', models.CharField(blank=True, choices=[('OK', 'OK'), ('KO', 'KO'), ('NA', 'NA')], max_length=100)),
                ('etat_sodure_iq', models.CharField(blank=True, choices=[('OK', 'OK'), ('KO', 'KO'), ('NA', 'NA')], max_length=100)),
                ('accept_date', models.DateField(blank=True, null=True)),
                ('accept_signa', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
