# Generated by Django 5.1.6 on 2025-06-11 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_validationframeserviceoutillage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationOutillageIgenQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marquage_num_out_iq', models.CharField(blank=True, choices=[('OK', 'OK'), ('KO', 'KO'), ('NA', 'NA')], max_length=100)),
                ('outillage_conforme_iq', models.CharField(blank=True, choices=[('OK', 'OK'), ('KO', 'KO'), ('NA', 'NA')], max_length=100)),
                ('page_arret_iq', models.CharField(blank=True, choices=[('OK', 'OK'), ('KO', 'KO'), ('NA', 'NA')], max_length=100)),
                ('outillage_propre_iq', models.CharField(blank=True, choices=[('OK', 'OK'), ('KO', 'KO'), ('NA', 'NA')], max_length=100)),
                ('presence_chaine_iq', models.CharField(blank=True, choices=[('OK', 'OK'), ('KO', 'KO'), ('NA', 'NA')], max_length=100)),
                ('presence_goupile_iq', models.CharField(blank=True, choices=[('OK', 'OK'), ('KO', 'KO'), ('NA', 'NA')], max_length=100)),
                ('page_plaquette_iq', models.CharField(blank=True, choices=[('OK', 'OK'), ('KO', 'KO'), ('NA', 'NA')], max_length=100)),
                ('accept_date', models.DateField(blank=True, null=True)),
                ('accept_signa', models.CharField(blank=True, max_length=200)),
                ('carte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validationoutillageingquality', to='core.acceptcarte')),
            ],
        ),
    ]
