# Generated by Django 5.1.6 on 2025-06-11 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_validationoutillageigenquality'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationframeingquality',
            name='carte',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validationframeingquality', to='core.acceptcarte'),
        ),
        migrations.AddField(
            model_name='validationframeserviceoutillage',
            name='carte',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validationframeso', to='core.acceptcarte'),
        ),
        migrations.AlterField(
            model_name='ordercarteacceptation',
            name='carte',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='core.acceptcarte'),
        ),
        migrations.AlterField(
            model_name='validationframechefoutillage',
            name='carte',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validationframechefoutillage', to='core.acceptcarte'),
        ),
        migrations.AlterField(
            model_name='validationoutillageigenquality',
            name='carte',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validationoutillageingquality', to='core.acceptcarte'),
        ),
    ]
