# Generated by Django 5.1.6 on 2025-06-11 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_validationframeingquality_carte_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderCarteAcceptation',
        ),
    ]
