# Generated by Django 5.1.6 on 2025-06-11 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_ordercarteacceptation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curative',
            fields=[
                ('maintenance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.maintenance')),
                ('date_propose_par_demandeur', models.DateField(auto_now_add=True, null=True)),
                ('heure_propose_par_demandeur', models.CharField(blank=True, max_length=50, null=True)),
                ('date_propose_par_mecancien', models.DateField(blank=True, null=True)),
                ('heure_propose_par_mecancien', models.CharField(blank=True, max_length=50, null=True)),
                ('type_intervention', models.CharField(blank=True, choices=[('Réparation', 'Réparation'), ('Modernisation', 'Modernisation')], max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('type_outillage', models.CharField(blank=True, choices=[('Frame', 'Frame'), ('Moule', 'Moule'), ('Tulip', 'Tulip'), ('Jaws', 'Jaws')], max_length=100)),
                ('atelier', models.CharField(blank=True, choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('B4', 'B4'), ('RSO', 'RSO')], max_length=50)),
                ('numero_outillage', models.CharField(blank=True, max_length=50)),
                ('ref', models.CharField(blank=True, max_length=50)),
                ('type_problem', models.CharField(blank=True, choices=[('Réparation des mors', 'Réparation des mors'), ('Régéneration du tulip', 'Régéneration du tulip'), ('Géométrie non-conforme', 'Géométrie non-conforme'), ('Changement du ressort', 'Changement du ressort'), ('Changement du numérotaion', 'Changement du numérotaion'), ('Fuit (sim/or)', 'Fuit (sim/or)'), ('Sodage', 'Sodage'), ('Poncage/polissage', 'Poncage/polissage'), ('Changement d`outillage', 'Changement d`outillage'), ('Changement de mec de sortie', 'Changement de mec de sortie')], max_length=300)),
                ('demandeur', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('core.maintenance',),
        ),
    ]
