# Generated by Django 5.1.6 on 2025-06-11 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_curative'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCarteAcceptation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=200)),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('type_outillage', models.CharField(blank=True, choices=[('Frame', 'Frame'), ('Moule', 'Moule'), ('Tulipe', 'Tulipe'), ('Jaws', 'Jaws')], max_length=100)),
                ('numero_outillage', models.CharField(blank=True, max_length=50)),
                ('ref', models.CharField(blank=True, max_length=50)),
                ('indice', models.CharField(blank=True, max_length=50)),
                ('rmq', models.CharField(blank=True, max_length=200)),
                ('date_ordre', models.DateField(blank=True, null=True)),
                ('carte', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='core.acceptcarte')),
            ],
        ),
    ]
