# Generated by Django 5.1.6 on 2025-06-11 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_ordercarteacceptation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationOutillageServiceOutillage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marquage_num_out_so', models.CharField(blank=True, choices=[('OK', 'OK'), ('KO', 'KO'), ('NA', 'NA')], max_length=100)),
                ('outillage_conforme_so', models.CharField(blank=True, choices=[('OK', 'OK'), ('KO', 'KO'), ('NA', 'NA')], max_length=100)),
                ('page_arret_so', models.CharField(blank=True, choices=[('OK', 'OK'), ('KO', 'KO'), ('NA', 'NA')], max_length=100)),
                ('outillage_propre_so', models.CharField(blank=True, choices=[('OK', 'OK'), ('KO', 'KO'), ('NA', 'NA')], max_length=100)),
                ('presence_chaine_so', models.CharField(blank=True, choices=[('OK', 'OK'), ('KO', 'KO'), ('NA', 'NA')], max_length=100)),
                ('presence_goupile_so', models.CharField(blank=True, choices=[('OK', 'OK'), ('KO', 'KO'), ('NA', 'NA')], max_length=100)),
                ('page_plaquette_so', models.CharField(blank=True, choices=[('OK', 'OK'), ('KO', 'KO'), ('NA', 'NA')], max_length=100)),
                ('accept_date', models.DateField(blank=True, null=True)),
                ('accept_signa', models.CharField(blank=True, max_length=200)),
                ('carte', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validationoutillageso', to='core.acceptcarte')),
            ],
        ),
    ]
