# Generated by Django 5.1.6 on 2025-06-11 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_validationoutillageserviceoutillage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curative',
            name='demandeur',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
