# Generated by Django 5.1.6 on 2025-06-11 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_curative_demandeur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acceptcarte',
            old_name='manif',
            new_name='manifacturation',
        ),
    ]
