# Generated by Django 5.1.6 on 2025-06-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_manif_acceptcarte_manifacturation'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptcarte',
            name='prod_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
