# Generated by Django 5.1.6 on 2025-06-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_acceptcarte_prod_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acceptcarte',
            old_name='prod_name',
            new_name='nom',
        ),
        migrations.AddField(
            model_name='acceptcarte',
            name='date_ordre',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acceptcarte',
            name='indice',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='acceptcarte',
            name='numero_outillage',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='acceptcarte',
            name='ref',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='acceptcarte',
            name='rmq',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='acceptcarte',
            name='titre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='acceptcarte',
            name='type_outillage',
            field=models.CharField(blank=True, choices=[('Frame', 'Frame'), ('Moule', 'Moule'), ('Tulipe', 'Tulipe'), ('Jaws', 'Jaws')], max_length=100),
        ),
    ]
