# Generated by Django 5.1.6 on 2025-06-12 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_prod_name_acceptcarte_nom_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderCarteAcceptation',
        ),
    ]
