# Generated by Django 5.1.6 on 2025-06-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_manifacturation_semaine'),
    ]

    operations = [
        migrations.CreateModel(
            name='NVoutillage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('type_outillage', models.CharField(blank=True, choices=[('Frame', 'Frame'), ('Moule', 'Moule'), ('Tulip', 'Tulip'), ('Jaws', 'Jaws'), ('Pin', 'Pin'), ('Elargisseur', 'Elargisseur')], max_length=100)),
                ('date_dentre', models.DateField(blank=True, null=True)),
                ('numero_outillage', models.CharField(blank=True, max_length=50)),
                ('conformite', models.CharField(blank=True, choices=[('OK', 'OK'), ('KO', 'KO')], max_length=100)),
                ('nombre_outillage', models.CharField(blank=True, max_length=50)),
                ('projet', models.CharField(blank=True, max_length=50)),
                ('validite_finale', models.CharField(blank=True, choices=[('Valide', 'Valide'), ('Invalide', 'Invalide')], max_length=100)),
            ],
        ),
    ]
