# Generated by Django 5.1.6 on 2025-06-19 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_nvoutillage_created_at_nvoutillage_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nvoutillage',
            name='nombre_outillage',
        ),
    ]
