# Generated by Django 5.1.6 on 2025-06-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_nvoutillage_nombre_outillage'),
    ]

    operations = [
        migrations.AddField(
            model_name='nvoutillage',
            name='notes',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
