# Generated by Django 5.1.6 on 2025-06-19 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_nvoutillage_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutillageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255)),
                ('type_outillage', models.CharField(max_length=255)),
                ('date_dentre', models.DateField()),
                ('numero_outillage', models.CharField(max_length=255)),
                ('conformite', models.CharField(max_length=10)),
                ('projet', models.CharField(max_length=255)),
                ('validite_finale', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('outillage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.nvoutillage')),
            ],
        ),
    ]
