# Generated by Django 5.1.6 on 2025-06-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_outillagehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifacturation',
            name='longeur',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manifacturation',
            name='nombre_canaux',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manifacturation',
            name='ref_frame',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
