# Generated by Django 5.1.6 on 2025-06-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_manifacturation_longeur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifacturation',
            name='nombre_canaux',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
