# Generated by Django 5.1.6 on 2025-06-20 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_manifacturation_nombre_canaux'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifacturation',
            name='quantity_produced',
        ),
    ]
