# Generated by Django 5.1.6 on 2025-06-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_manifacturation_quantity_produced'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifacturation',
            name='num_outillage',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
