# Generated by Django 5.1.6 on 2025-06-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_manifacturation_num_outillage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstock',
            name='seuil_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='seuil_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
