# Generated by Django 5.1.6 on 2025-06-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_historicalstock_seuil_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstock',
            name='seuil_min',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='seuil_min',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
