# Generated by Django 5.1.6 on 2025-06-25 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_historicalstock_seuil_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity_added',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity_removed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
