# Generated by Django 5.1.6 on 2025-06-25 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_inventory_quantity_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstock',
            name='location',
            field=models.CharField(blank=True, choices=[('Block A', 'Block A'), ('Block B', 'Block B'), ('Block A/B', 'Block A/B')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='location',
            field=models.CharField(blank=True, choices=[('Block A', 'Block A'), ('Block B', 'Block B'), ('Block A/B', 'Block A/B')], max_length=50),
        ),
    ]
