# Generated by Django 5.1.6 on 2025-06-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_historicalstock_location_alter_stock_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventive',
            name='frequency',
            field=models.PositiveIntegerField(blank=True, help_text='Months between maintenance', null=True),
        ),
        migrations.AddField(
            model_name='preventive',
            name='next_due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
