# Generated by Django 5.1.6 on 2025-06-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_preventive_frequency_preventive_next_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptcarte',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='acceptcarte',
            name='date_ordre',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='preventive',
            name='frequency',
            field=models.PositiveIntegerField(default=1, help_text='Days between maintenance'),
        ),
    ]
