# Generated by Django 5.1.6 on 2025-06-30 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_acceptcarte_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curative',
            name='outilleur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='curatives_outilleur', to=settings.AUTH_USER_MODEL),
        ),
    ]
