# Generated by Django 5.1.6 on 2025-06-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='semaine',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
