# Generated by Django 5.1.6 on 2025-06-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_availability_semaine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifacturation',
            name='semaine',
            field=models.IntegerField(blank=True, choices=[(1, 'S1'), (2, 'S2'), (3, 'S3'), (4, 'S4'), (5, 'S5'), (6, 'S6'), (7, 'S7'), (8, 'S8'), (9, 'S9'), (10, 'S10'), (11, 'S11'), (12, 'S12'), (13, 'S13'), (14, 'S14'), (15, 'S15'), (16, 'S16'), (17, 'S17'), (18, 'S18'), (19, 'S19'), (20, 'S20'), (21, 'S21'), (22, 'S22'), (23, 'S23'), (24, 'S24'), (25, 'S25'), (26, 'S26'), (27, 'S27'), (28, 'S28'), (29, 'S29'), (30, 'S30'), (31, 'S31'), (32, 'S32'), (33, 'S33'), (34, 'S34'), (35, 'S35'), (36, 'S36'), (37, 'S37'), (38, 'S38'), (39, 'S39'), (40, 'S40'), (41, 'S41'), (42, 'S42'), (43, 'S43'), (44, 'S44'), (45, 'S45'), (46, 'S46'), (47, 'S47'), (48, 'S48'), (49, 'S49'), (50, 'S50'), (51, 'S51'), (52, 'S52')]),
        ),
    ]
