# Generated by Django 5.1.6 on 2025-06-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_manifacturation_semaine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifacturation',
            name='semaine',
            field=models.CharField(blank=True, choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4'), ('S5', 'S5'), ('S6', 'S6'), ('S7', 'S7'), ('S8', 'S8'), ('S9', 'S9'), ('S10', 'S10'), ('S11', 'S11'), ('S12', 'S12'), ('S13', 'S13'), ('S14', 'S14'), ('S15', 'S15'), ('S16', 'S16'), ('S17', 'S17'), ('S18', 'S18'), ('S19', 'S19'), ('S20', 'S20'), ('S21', 'S21'), ('S22', 'S22'), ('S23', 'S23'), ('S24', 'S24'), ('S25', 'S25'), ('S26', 'S26'), ('S27', 'S27'), ('S28', 'S28'), ('S29', 'S29'), ('S30', 'S30'), ('S31', 'S31'), ('S32', 'S32'), ('S33', 'S33'), ('S34', 'S34'), ('S35', 'S35'), ('S36', 'S36'), ('S37', 'S37'), ('S38', 'S38'), ('S39', 'S39'), ('S40', 'S40'), ('S41', 'S41'), ('S42', 'S42'), ('S43', 'S43'), ('S44', 'S44'), ('S45', 'S45'), ('S46', 'S46'), ('S47', 'S47'), ('S48', 'S48'), ('S49', 'S49'), ('S50', 'S50'), ('S51', 'S51'), ('S52', 'S52')], max_length=10),
        ),
    ]
