# Generated by Django 5.1.6 on 2025-06-30 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_manifacturation_semaine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifacturation',
            name='semaine',
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
