# Generated by Django 5.1.6 on 2025-06-30 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_manifacturation_semaine_delete_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preventive',
            old_name='next_due',
            new_name='next_due_date',
        ),
    ]
