# Generated by Django 5.1.6 on 2025-07-01 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_rename_next_due_preventive_next_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preventive',
            name='gamme_operatoire_main',
        ),
    ]
