# Generated by Django 5.1.6 on 2025-07-01 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_remove_preventive_gamme_operatoire_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preventive',
            name='next_due_date',
        ),
    ]
