# Generated by Django 5.1.6 on 2025-07-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_remove_preventive_next_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventive',
            name='frequency',
            field=models.CharField(choices=[('1', '1 mois'), ('2', '2 mois'), ('3', '3 mois'), ('4', '4 mois'), ('6', '6 mois')], default='1', help_text='Fréquence de maintenance en mois', max_length=2),
        ),
    ]
