# Generated by Django 5.1.6 on 2025-07-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_preventive_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventive',
            name='frequency',
            field=models.CharField(choices=[('1 month', '1 mois'), ('2 months', '2 mois'), ('3 months', '3 mois'), ('4 months', '4 mois'), ('6 months', '6 mois')], max_length=20),
        ),
    ]
