# Generated by Django 5.1.6 on 2025-07-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_preventive_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationframechefoutillage',
            name='accept_signa',
            field=models.CharField(blank=True, choices=[('Valide', 'Valide'), ('Invalide', 'Invalide')], max_length=200),
        ),
        migrations.AlterField(
            model_name='validationframeingquality',
            name='accept_signa',
            field=models.CharField(blank=True, choices=[('Valide', 'Valide'), ('Invalide', 'Invalide')], max_length=200),
        ),
        migrations.AlterField(
            model_name='validationframeserviceoutillage',
            name='accept_signa',
            field=models.CharField(blank=True, choices=[('Valide', 'Valide'), ('Invalide', 'Invalide')], max_length=200),
        ),
    ]
