# Generated by Django 5.1.6 on 2025-07-04 12:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_validationframechefoutillage_accept_signa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validationframechefoutillage',
            name='accept_signa',
        ),
        migrations.RemoveField(
            model_name='validationframeingquality',
            name='accept_signa',
        ),
        migrations.RemoveField(
            model_name='validationframeserviceoutillage',
            name='accept_signa',
        ),
        migrations.AlterField(
            model_name='manifacturation',
            name='longeur',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='manifacturation',
            name='nombre_canaux',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
