# Generated by Django 5.1.6 on 2025-07-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_remove_validationframechefoutillage_accept_signa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifacturation',
            name='longeur',
            field=models.IntegerField(blank=True),
        ),
    ]
