# Generated by Django 5.1.6 on 2025-07-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_manifacturation_longeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifacturation',
            name='longeur',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
