# Generated by Django 5.1.6 on 2025-07-07 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_manifacturation_longeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curative',
            name='type_outillage',
            field=models.CharField(blank=True, choices=[('Frame', 'Frame'), ('Moule', 'Moule'), ('Tulip', 'Tulip'), ('Jaws', 'Jaws'), ('Head', 'Head'), ('Autre', 'Autre')], max_length=100),
        ),
        migrations.AlterField(
            model_name='curative',
            name='type_problem',
            field=models.CharField(blank=True, choices=[('Réparation des mors', 'Réparation des mors'), ('Régéneration du tulip', 'Régéneration du tulip'), ('Géométrie non-conforme', 'Géométrie non-conforme'), ('Changement du ressort', 'Changement du ressort'), ('Changement du numérotaion', 'Changement du numérotaion'), ('Fuit (sim/or)', 'Fuit (sim/or)'), ('Sodage', 'Sodage'), ('Poncage/polissage', 'Poncage/polissage'), ('Changement d`outillage', 'Changement d`outillage'), ('Changement de mec de sortie', 'Changement de mec de sortie'), ('Autre', 'Autre')], max_length=300),
        ),
        migrations.AlterField(
            model_name='order',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.article'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_commande',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='etat_commande',
            field=models.CharField(blank=True, choices=[('commandé', 'commandé'), ('a commandé', 'a commandé'), ('recue', 'recue')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity_cmd',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.supplier'),
        ),
    ]
