# Generated by Django 5.1.6 on 2025-07-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_curative_type_outillage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='etat_commande',
            field=models.CharField(blank=True, choices=[('commandé', 'commandé'), ('a commandé', 'a commandé'), ('recue', 'recue')], default='a commandé', max_length=50),
        ),
    ]
