# Generated by Django 5.1.6 on 2025-07-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_order_etat_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_commande',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_livraison',
            field=models.DateField(blank=True, null=True),
        ),
    ]
