# Generated by Django 5.1.6 on 2025-07-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_order_date_commande_alter_order_date_livraison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity_cmd',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
