# Generated by Django 5.1.6 on 2025-07-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_order_quantity_cmd'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='prix',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
