# Generated by Django 5.1.6 on 2025-07-09 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_article_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='project_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='planning',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fabriquant_planning', to=settings.AUTH_USER_MODEL),
        ),
    ]
