# Generated by Django 5.1.6 on 2025-07-13 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_planning_project_leader_alter_planning_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockhistory',
            options={},
        ),
        migrations.RenameField(
            model_name='stockhistory',
            old_name='recieved_commands',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='stockhistory',
            old_name='totale_quatity_used',
            new_name='received_commands',
        ),
        migrations.RemoveField(
            model_name='planning',
            name='project_leader',
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='date_recorded',
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='ending_quantity',
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='starting_quantity',
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='week',
        ),
        migrations.AddField(
            model_name='manifacturation',
            name='longeurFt1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='manifacturation',
            name='longeurFt2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='manifacturation',
            name='longeurFt3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='manifacturation',
            name='longeurFt4',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='manifacturation',
            name='programme',
            field=models.CharField(blank=True, choices=[('Four', 'Four'), ('Autre', 'Autre')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='manifacturation',
            name='project_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='a_commande',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.article'),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='consomation_annuelle',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='delai_approvisionnement',
            field=models.CharField(blank=True, choices=[('1 semaine', '1 semaine'), ('2 semaines', '2 semaines'), ('3 semaines', '3 semaines'), ('4 semaines', '4 semaines'), ('5 semaines', '5 semaines'), ('6 semaines', '6 semaines'), ('7 semaines', '7 semaines'), ('8 semaines', '8 semaines'), ('9 semaines', '9 semaines'), ('10 semaines', '10 semaines'), ('11 semaines', '11 semaines'), ('12 semaines', '12 semaines')], default='1 semaine', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='location',
            field=models.CharField(blank=True, choices=[('Block A', 'Block A'), ('Block B', 'Block B'), ('Block A/B', 'Block A/B')], max_length=50),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='reorder_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='seuil_min',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='total_quantity_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='manifacturation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fabriquant_planning', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='outillagehistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='planning',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='ecart_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='virtual_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
