# Generated by Django 5.1.6 on 2025-07-13 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_stockhistory_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockHistory',
        ),
    ]
