# Generated by Django 5.1.6 on 2025-07-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_delete_stockhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=10)),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('starting_quantity', models.IntegerField()),
                ('recieved_commands', models.IntegerField(default=0)),
                ('totale_quatity_used', models.IntegerField(default=0)),
                ('ending_quantity', models.IntegerField()),
                ('virtual_stock', models.IntegerField()),
                ('ecart_stock', models.IntegerField()),
            ],
            options={
                'ordering': ['-date_recorded'],
            },
        ),
    ]
