# Generated by Django 5.1.6 on 2025-07-13 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_stockhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('received_commands', models.IntegerField(default=0)),
                ('total_quantity_used', models.IntegerField(default=0)),
                ('consomation_annuelle', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, choices=[('Block A', 'Block A'), ('Block B', 'Block B'), ('Block A/B', 'Block A/B')], max_length=50)),
                ('reorder_level', models.IntegerField(blank=True, null=True)),
                ('delai_approvisionnement', models.CharField(blank=True, choices=[('1 semaine', '1 semaine'), ('2 semaines', '2 semaines'), ('3 semaines', '3 semaines'), ('4 semaines', '4 semaines'), ('5 semaines', '5 semaines'), ('6 semaines', '6 semaines'), ('7 semaines', '7 semaines'), ('8 semaines', '8 semaines'), ('9 semaines', '9 semaines'), ('10 semaines', '10 semaines'), ('11 semaines', '11 semaines'), ('12 semaines', '12 semaines')], default='1 semaine', max_length=100, null=True)),
                ('seuil_min', models.IntegerField(blank=True, default=0, null=True)),
                ('virtual_stock', models.IntegerField(blank=True, null=True)),
                ('ecart_stock', models.IntegerField(blank=True, null=True)),
                ('a_commande', models.IntegerField(blank=True, default=0)),
                ('updated_at', models.DateField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.article')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.stock')),
            ],
        ),
    ]
