# Generated by Django 5.1.6 on 2025-07-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_historiquestock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifacturation',
            name='programme',
            field=models.CharField(blank=True, choices=[('Four', 'Four'), ('Wintec', 'Wintec')], default='', max_length=100),
        ),
    ]
