# Generated by Django 5.1.6 on 2025-07-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_alter_manifacturation_programme'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifacturation',
            name='tulipe',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
