# Generated by Django 5.1.6 on 2025-07-14 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_manifacturation_tulipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifacturation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fabriquant_planning', to=settings.AUTH_USER_MODEL),
        ),
    ]
