# Generated by Django 5.1.6 on 2025-07-14 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_alter_manifacturation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquestock',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_entries', to='core.stock'),
        ),
    ]
